### ISSUE TITLE
在配置文件中找不到名为 'setting' 的部分（section）

### ISSUE THREAD

**Issue by 316yangguang** [XYZliang/JiangxiYouthStudyMaker#27]
![image](https://github.com/XYZliang/JiangxiYouthStudyMaker/assets/118321048/1ebb9bb8-07be-4ccf-9fed-07a755a104fd)
C:\Users\31626>python E:\dowlnoad\JiangxiYouthStudyMaker-main\批量多人提交版\批量获取历史数据.py
Traceback (most recent call last):
  File "E:\dowlnoad\JiangxiYouthStudyMaker-main\批量多人提交版\批量获取历史数据.py", line 22, in <module>
    limit = config.getint('setting', 'limit')
  File "D:\development\Python3.10.9\lib\configparser.py", line 819, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "D:\development\Python3.10.9\lib\configparser.py", line 809, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "D:\development\Python3.10.9\lib\configparser.py", line 804, in _get
    return conv(self.get(section, option, **kwargs))
  File "D:\development\Python3.10.9\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "D:\development\Python3.10.9\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'setting'

这是什么问题呀

**Comment by XYZliang** [comment]
最近会更新新版本，后面更新了你再试试看
